config/routes.rb
# encoding: UTF-8
# frozen_string_literal: true

# Explicitly require "lib/peatio.rb".
# You may be surprised why this line also sits in config/application.rb.
# The same line sits in config/application.rb to allows early access to lib/peatio.rb.
# We duplicate line in config/routes.rb since routes.rb is reloaded when code is changed.
# The implementation of ActiveSupport's require_dependency makes sense to use it only in reloadable files.
# That's why it is here.
require_dependency 'peatio'

Dir['app/models/deposits/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }
Dir['app/models/withdraws/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do

  root 'welcome#index'
  
  get 'welcome/privacy_policy'

  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: %i[get post]

  scope module: :private do
    #resources :settings, only: [:index]
    resources :settings, only: [:index] do
      match :change_password, on: :collection, via: %w(get put)
      match :verify_contact, on: :collection, via: %w(get post put)
      match :update_profile, on: :collection, via: %w(get post)
      match :upload_documents, on: :collection, via: %w(get post)
      collection do 
        post 'change_avatar'
      end
    end
    resources :withdraw_destinations, only: %i[ create update ]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    resources 'deposits/:currency', controller: 'deposits', as: 'deposit', only: %i[ destroy ] do
      collection { post 'gen_address' }
    end

    resources 'withdraws/:currency', controller: 'withdraws', as: 'withdraw', only: %i[ create destroy ]

    resources :account_versions, only: :index

    resources :exchange_assets, controller: 'assets'

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, only: [:show], constraints: MarketConstraint do
      resources :orders, only: %i[ index destroy ] do
        collection do
          post :clear
        end
      end
      resources :order_bids, only: [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, only: [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'
  end

  get 'trading/:market_id', to: BlackHoleRouter.new, as: :trading

  scope ['', 'webhooks', ENV['WEBHOOKS_SECURE_URL_COMPONENT'].presence, ':ccy'].compact.join('/'), as: 'webhooks' do
    post 'tx_created', to: 'webhooks#tx_created'
  end

  draw :admin

  get '/swagger', to: 'swagger#index'

  mount APIv2::Mount => APIv2::Mount::PREFIX
  mount ManagementAPIv1::Mount => ManagementAPIv1::Mount::PREFIX
end

app/views/shared/_admin_header_profile_setting.html.erb
<% controllers = ['settings', 'dashboard'] %>
<% dropdown_class = (controllers & controller_path.split('/')).empty? ? '' : 'active' %>
<li class="nav-item dropdown account-settings text-left <%= dropdown_class %>">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <span><%= current_user.email %></span>
    <span class="caret"></span>
    <span class="text-muted setting-txt">settings</span>
  </a>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="<%= settings_path %>">
      <i class="fa fa-cog"></i><span><%= t('header.Settings') %></span>
    </a>
    <% if is_admin? %>
      <a class="dropdown-item" href="<%= admin_dashboard_path %>">
        <i class="fa fa-dashboard"></i>
        <span><%= t('header.admin') %></span>
      </a>
    <% end %>
    <a class="dropdown-item" href="<%= main_app.signout_path %>">
      <i class="fa fa-sign-out"></i>
      <span><%= t('header.signout') %></span>
    </a>
  </div>
</li>

app/views/shared/_flash.html.erb
<div class="flash-message">
  <% if flash[:notice] %>
    <div class="alert alert-dismissable alert-custom-success alert-success">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:notice] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-dismissable alert-custom-danger alert-danger">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-times"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:alert] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:info] %>
    <div class="alert alert-dismissable alert-custom-info alert-info">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-info"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:info] %></span>
      </h2>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid ">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <footer class="footer">
        <p>&copy; 2017 Caishen - All Rights Reserved.</p>
        <ul>
          <li><a href="javascript:;">What is Caishen?</a></li>
          <li><%= link_to "Privacy policy" ,welcome_privacy_policy_path%></li>
          <li><a href="javascript:;">Terms of Use</a></li>
          <li><a href="javascript:;">Fees</a></li>
        </ul>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_frame.html.erb
<div class="container-fluid">
  <div id="content" class="col-8">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
  <% if content_for?(:before) %>
    <%= yield(:before) %>
  <% end %>
  <div class="card card-default">
    <div class="card-header">
      <h2 class="card-title"><%= guide_panel_title %></h2>
    </div>
    <div class="card-body">
      <div class="row">
        <div id="guide" class="col-4">
          <% if content_for?(:guide_title) %>
            <%= yield(:guide_title) %>
          <% else %>
            <h3><%= guide_title %></h3>
          <% end %>
          <p class="text-ignore"><%= guide_intro %></p>
          <% if content_for?(:guide) %>
            <%= yield(:guide) %>
          <% end %>
        </div>
      </div>
      <% if content_for?(:secondary) %>
        <%= yield(:secondary) %>
      <% end %>
    </div>
  </div>
  <% if content_for?(:after) %>
    <%= yield(:after) %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="../assets/logo.png" />
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= top_nav_link(t('header.market'), trading_path(current_market.id), 'exchange', target: '_blank') if current_user %></li>
        <li><%= top_nav_link(t('header.funds'), funds_path, 'money', controllers: ['funds']) if current_user %></li>
        <li><%= top_nav_link(t('header.assets'), exchange_assets_path, 'bar-chart-o') if current_user %></li>
        <li><%= top_nav_link(t('header.history'), order_history_path, 'book', controllers: ['history']) if current_user %></li>
        <% if current_user %>
          <li><a href="<%= main_app.signout_path %>"><i class="fa fa-fw fa-power-off"></i> Logout</a></li>
        <% end %>  
        
        <% unless current_user %>
          <li><a class="btn btn-primary" href="http://auth.caishen.exchange/accounts/sign_up" role="button">Get Started</a></li>
          <% provider = ENV['OAUTH2_SIGN_IN_PROVIDER'] %>
          <% unless provider.blank? %>
            <a class="btn btn-default" href="/auth/<%= provider == 'google' ? 'google_oauth2' : provider %>">
              <small>Login</small>
            </a>
          <% end %>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_header_lang_sel.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <img src="/languages/<%= I18n.locale %>.png"/>
    <b class="caret"></b>
  </a>
  <div id="languages" class="dropdown-menu">
    <% I18n.available_locales.each do |lang| %>
      <a class="dropdown-item" href="?lang=<%= lang %>">
        <img src="/languages/<%= lang || I18n.locale %>.png"/>
      </a>
    <% end %>
  </div>
</li>

app/views/shared/_header_profile_setting.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="/assets/logo1.png" alt="LOGO">
        </a>
    </div>
    <div class="toptitle">
      <h3><%= controller.controller_name.capitalize %></h3>
    </div>
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a id="user-profile" href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="/assets/admin.png" class="img-responsive img-thumbnail img-circle"><%= current_user.email %><b class="fa fa-angle-down"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#"><i class="fa fa-fw fa-user"></i> Edit Profile</a></li>
                <li><a href="#"><i class="fa fa-fw fa-cog"></i> Password</a></li>
                <li class="divider"></li>
                <li><a href="<%= main_app.signout_path %>"><i class="fa fa-fw fa-power-off"></i> Logout</a></li>
            </ul>
        </li>
        <li class="alertbell"><a href="#"><i class="fa fa-bell-o"></i> <sup>2</sup></a></li>
    </ul>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li class="sidelogo">
              <a href="<%= root_path %>"> <img src="/assets/logo.png" alt="LOGO"></a>
            </li>
            <li>
                <a href="<%= settings_path %>"><i class="fa fa-fw fa-cog"></i>  My Account</a>
            </li>
            <li>
                <a href="<%= trading_path(current_market.id) %>"><i class="fa fa-fw fa-question-circle"></i> Exchange</a>
            </li>
            <li>
                <a href="<%= funds_path %>"><i class="fa fa-fw fa-money"></i> Funds</a>
            </li>
            <li>
              <a href="<%= exchange_assets_path %>"><i class="fa fa-fw fa fa-bar-chart"></i> Solvency</a>
            </li>
            <li>
              <a href="<%= order_history_path %>"><i class="fa fa-fw fa-file-o"></i> History</a>
            </li>
            <li>
                <a href="javascript:;"><i class="fa fa-fw fa-question-circle"></i> About Chaisen</a>
            </li>
        </ul>
    </div>
</nav>

app/views/shared/_meta.html.erb
<title><%= ENV.fetch('METADATA_TITLE') %></title>
<meta name="description" content="<%= ENV.fetch('METADATA_DESCRIPTION') %>">
<meta name="keywords" content="<%= ENV.fetch('METADATA_KEYWORDS') %>">

app/views/shared/_sentry.html.erb
<% if defined?(Raven) && ENV['SENTRY_DSN_FRONTEND'].present? %>
    <meta name="sentry-dsn" content="<%= ENV['SENTRY_DSN_FRONTEND'] %>">
<% end %>