config/routes.rb
# encoding: UTF-8
# frozen_string_literal: true

# Explicitly require "lib/peatio.rb".
# You may be surprised why this line also sits in config/application.rb.
# The same line sits in config/application.rb to allows early access to lib/peatio.rb.
# We duplicate line in config/routes.rb since routes.rb is reloaded when code is changed.
# The implementation of ActiveSupport's require_dependency makes sense to use it only in reloadable files.
# That's why it is here.
require_dependency 'peatio'

Dir['app/models/deposits/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }
Dir['app/models/withdraws/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do

  root 'welcome#index'
  
  get 'welcome/privacy_policy'

  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: %i[get post]

  scope module: :private do
    #resources :settings, only: [:index]
    resources :settings, only: [:index] do
      match :change_password, on: :collection, via: %w(get put)
      match :verify_contact, on: :collection, via: %w(get post put)
      match :update_profile, on: :collection, via: %w(get post)
      match :upload_documents, on: :collection, via: %w(get post)
      collection do 
        post 'change_avatar'
      end
    end
    resources :withdraw_destinations, only: %i[ create update ]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    resources 'deposits/:currency', controller: 'deposits', as: 'deposit', only: %i[ destroy ] do
      collection { post 'gen_address' }
    end

    resources 'withdraws/:currency', controller: 'withdraws', as: 'withdraw', only: %i[ create destroy ]

    resources :account_versions, only: :index

    resources :exchange_assets, controller: 'assets'

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, only: [:show], constraints: MarketConstraint do
      resources :orders, only: %i[ index destroy ] do
        collection do
          post :clear
        end
      end
      resources :order_bids, only: [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, only: [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'
  end

  get 'trading/:market_id', to: BlackHoleRouter.new, as: :trading

  scope ['', 'webhooks', ENV['WEBHOOKS_SECURE_URL_COMPONENT'].presence, ':ccy'].compact.join('/'), as: 'webhooks' do
    post 'tx_created', to: 'webhooks#tx_created'
  end

  draw :admin

  get '/swagger', to: 'swagger#index'

  mount APIv2::Mount => APIv2::Mount::PREFIX
  mount ManagementAPIv1::Mount => ManagementAPIv1::Mount::PREFIX
end

app/controllers/private/account_versions_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class AccountVersionsController < BaseController
    def index
      @account_versions_grid = AccountVersionsGrid.new(params[:account_versions_grid]) do |scope|
        scope.where(:member_id => current_user.id)
      end
      @assets = @account_versions_grid.assets.page(params[:page]).per(20)
    end
  end
end

app/controllers/private/assets_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class AssetsController < BaseController
    skip_before_action :auth_member!, only: [:index]

    def index
      Currency.all.each do |ccy|
        name = ccy.fiat? ? :fiat : ccy.code.to_sym
        instance_variable_set :"@#{name}_proof", Proof.current(ccy.code.to_sym)
        if current_user
          instance_variable_set :"@#{name}_account", \
            current_user.accounts.with_currency(ccy.code.to_sym).first
        end
      end
    end
  end
end

app/controllers/private/base_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class BaseController < ::ApplicationController
    before_filter :no_cache, :auth_member!

    private

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Sat, 03 Jan 2009 00:00:00 GMT"
    end
  end
end

app/controllers/private/deposits_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class DepositsController < BaseController
    before_action :auth_verified!

    def gen_address
      current_user.get_account(currency).tap do |account|
        account.payment_address&.enqueue_address_generation
      end
      head 204
    end

    def destroy
      record = current_user.deposits.find(params[:id]).lock!
      if record.cancel!
        head 204
      else
        head 422
      end
    end

  private

    def currency
      @currency ||= Currency.find_by_code!(params[:currency])
    end
  end
end

app/controllers/private/funds_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class FundsController < BaseController
    include CurrencyHelper

    layout 'funds'

    before_action :auth_verified!

    def index
      @currencies        = Currency.all.sort
      @deposits          = current_user.deposits
      @accounts          = current_user.accounts.enabled
      @withdraws         = current_user.withdraws

      gon.jbuilder
    end

    helper_method :currency_icon_url

    def gen_address
      current_user.accounts.each do |account|
        account.payment_address&.enqueue_address_generation
      end
      render nothing: true
    end
  end
end

app/controllers/private/history_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class HistoryController < BaseController

    helper_method :tabs

    def account
      @market = current_market

      @deposits = Deposit.where(member: current_user).with_aasm_state(:accepted)
      @withdraws = Withdraw.where(member: current_user).with_aasm_state(:succeed)

      @transactions = (@deposits + @withdraws).sort_by {|t| -t.created_at.to_i }
      @transactions = Kaminari.paginate_array(@transactions).page(params[:page]).per(20)
    end

    def trades
      @trades = current_user.trades
        .includes(:ask_member).includes(:bid_member)
        .order('id desc').page(params[:page]).per(20)
    end

    def orders
      @orders = current_user.orders.includes(:trades).order("id desc").page(params[:page]).per(20)
    end

    private

    def tabs
      { order: ['header.order_history', order_history_path],
        trade: ['header.trade_history', trade_history_path],
        account: ['header.account_history', account_history_path] }
    end

  end
end

app/controllers/private/markets_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class MarketsController < BaseController
    include Concerns::DisableMarketsUI
    include CurrencyHelper

    skip_before_action :auth_member!, only: [:show]
    before_action :visible_market?
    after_action :set_default_market

    layout false

    def show
      @bid = params[:bid]
      @ask = params[:ask]

      @market        = current_market
      @markets       = Market.all
      @market_groups = @markets.map(&:ask_unit).uniq

      @bids   = @market.bids
      @asks   = @market.asks
      @trades = @market.trades

      # default to limit order
      @order_bid = OrderBid.new ord_type: 'limit'
      @order_ask = OrderAsk.new ord_type: 'limit'

      set_member_data if current_user
      gon.jbuilder
      render json: trading_ui_variables
    end

    private

    def visible_market?
      redirect_to trading_path(Market.first) unless current_market.visible?
    end

    def set_default_market
      cookies[:market_id] = @market.id
    end

    def set_member_data
      @member = current_user
      @orders_wait = @member.orders.where(market_id: @market).with_state(:wait)
      @trades_done = Trade.for_member(@market.id, current_user, limit: 100, order: 'id desc')
    end

    def trading_ui_variables
      accounts = @member&.accounts&.map do |x|
        { id:         x.id,
          locked:     x.locked,
          amount:     x.amount,
          currency:   {
            code:     x.currency.code,
            symbol:   x.currency.symbol,
            type:     x.currency.type,
            icon_url: currency_icon_url(x.currency) } }
      end

      { current_market: @market.as_json,
        gon_variables:  gon.all_variables,
        market_groups:  @market_groups,
        currencies:     Currency.order(id: :asc).map { |c| { code: c.code, type: c.type } },
        current_member: @member,
        markets:        @markets.map { |m| m.as_json.merge!(ticker: Global[m].ticker) },
        my_accounts:    accounts,
        csrf_token:     form_authenticity_token
      }
    end

  end
end

app/controllers/private/order_asks_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class OrderAsksController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderAsk.new(order_params(:order_ask))
      order_submit
    end

    def clear
      @orders = OrderAsk.where(member_id: current_user.id).with_state(:wait).with_market(current_market)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/order_bids_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class OrderBidsController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderBid.new(order_params(:order_bid))
      order_submit
    end

    def clear
      @orders = OrderBid.where(member_id: current_user.id).with_state(:wait).with_market(current_market)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/orders_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private
  class OrdersController < BaseController

    def destroy
      ActiveRecord::Base.transaction do
        order = current_user.orders.find(params[:id])
        ordering = Ordering.new(order)

        if ordering.cancel
          render status: 200, nothing: true
        else
          render status: 500, nothing: true
        end
      end
    end

    def clear
      @orders = current_user.orders.with_market(current_market).with_state(:wait)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/pusher_controller.rb
# encoding: UTF-8
# frozen_string_literal: true

require "openssl"

module Private
  class PusherController < BaseController
    protect_from_forgery :except => :auth
  
    def auth
      sn = params[:channel_name].split('-', 2).last
      if current_user && current_user.sn == sn
        response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
        render :json => response
      else
        render :text => "Forbidden", :status => '403'
      end
    end
  end
end

app/controllers/private/settings_controller.rb
module Private
  class SettingsController < BaseController
    before_action :set_previous_details, except: [:index, :change_password, :verify_contact, :referrals_process]
    before_action :set_member_and_status, except: [:index]

    def index
    end

    def change_avatar
      if @member.update(avatar: params[:avatar])
        redirect_to settings_path,alert: "Image updted successfully"
      else
        redirect_to settings_path,alert: "Please try again"
      end  
    end

    def change_password
      if request.put?
        begin
          abc = RestClient.put(
            "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/accounts/password",
            params.require(:member).permit!.merge({access_token: current_user.auth('barong').token})
          )
          @message = "Password Changed!"
          @status = true
        rescue => e
          @message = e.message
        end
      end
    end

    def verify_contact
      if request.put?
        begin
          phone_params = params.require(:member).permit(:country_code, :phone_number, :verification_code)
          phone_params[:phone_number] = phone_params.delete(:country_code)+phone_params.delete(:phone_number)
          abc = RestClient.post(
            "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/phones/verify",
            phone_params.merge({access_token: current_user.auth('barong').token})
          )
          @message = JSON.parse(abc.body)['message']
          @status = true
        rescue => e
          @message = e.message
        end
      elsif request.post?
        begin
          params.require(:phone_number) rescue (raise 'Phone Number is blank!')
          abc = RestClient.post(
            "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/phones",
            {phone_number: params.require(:phone_number)}.merge({access_token: current_user.auth('barong').token})
          )
          render json: {status: true, message: JSON.parse(abc.body)['message']}
        rescue => e
          render json: {status: false, message: e.message}
        end
      end
    end

    def update_profile
      if request.post?
        begin
          abc = RestClient.post(
            "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/profiles",
            profile_params.merge({access_token: current_user.auth('barong').token})
          )
          @status = true
          @message = "Profile Updated!"
        rescue => e
          @message = e.message
        end
      end
    end

    def upload_documents
      if request.post?
        begin
          abc = RestClient.post(
            "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/documents",
            upload_document_params.merge({access_token: current_user.auth('barong').token})
          )
          @status = true
          @message = "Document Uploaded!"
        rescue => e
          @message = e.message
        end
      end
    end

    def referrals_process
    end

    private
    def set_member_and_status
      @member = current_user
      @status = false
      @referred_members = current_user.referred_members.includes(:ref_member) if action_name=="referrals_process"
      render(partial: params[:action]) if request.get?
    end

    def set_previous_details
      if request.get?
        begin
          @current_details = RestClient.get(
            "#{previous_data_api}?access_token=#{current_user.auth('barong').token}"
          )
          @current_details = JSON.parse(@current_details.body) {}
        rescue 
           @current_details = {}
        end
      end
    end

    def previous_data_api
      {
        update_profile: "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/profiles/me",
        upload_documents: "#{ENV.fetch('BARONG_DOMAIN')}/api/v1/documents"
      }[params[:action].to_sym]
    end

    def profile_params
      member_params = params.require(:member)
      {
        first_name:   member_params.require(:first_name),
        last_name:    member_params.require(:last_name),
        dob:          member_params.require(:dob),
        address:      member_params.require(:address),
        postcode:     member_params.require(:postcode),
        city:         member_params.require(:city),
        country:      member_params.require(:country)
      }
    end

    def upload_document_params
      document_params = params.require(:document)
      {
        doc_expire:   document_params.require(:doc_expire),
        doc_type:     document_params.require(:doc_type),
        doc_number:   document_params.require(:doc_number),
        upload:       document_params.require(:upload)
      }
    end
  end
end

app/helpers/private/assets_helper.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private::AssetsHelper

  def verify_link(proof, partial_tree)
    hashtag = "verify?partial_tree=#{partial_tree.json.to_json}&expected_root=#{proof.root.to_json}"
    uri = "http://syskall.com/proof-of-liabilities/##{URI.encode hashtag}"
    link_to t('.go-verify'), uri, :class => 'btn btn-default', :target => '_blank'
  end

end

app/helpers/private/history_helper.rb
# encoding: UTF-8
# frozen_string_literal: true

module Private::HistoryHelper
  def trade_side(trade)
    trade.ask_member == current_user ? 'sell' : 'buy'
  end

  def transaction_type(t)
    t(".#{t.class.superclass.name}")
  end

  def transaction_txid_link(t)
    return t.txid if t.txid.blank? || !t.currency.coin?
    link_to t.txid, t.transaction_url
  end
end

app/helpers/private/setting_helper.rb
module Private::SettingHelper
	
	def display_country country=nil
    @countries = ISO3166::Country.all.sort
    options_for_select(@countries, country)
  end

  SEQUENCE_HASH = {
    'email_verified':     1,
    'phone_verified':     2,
    'document_verified':  3,
    'identity_verified':  4
  }

  def is_verified? level_check
    SEQUENCE_HASH[current_user.level.to_sym] >= level_check
  end

  def icons_tags_str  level_match_status
    level_match_status ?
     "<i class='fa fa-check-circle-o' aria-hidden='true' style='color: forestgreen;font-size: 25px;vertical-align: sub;'></i><span style='color: forestgreen;font-size: 14px;vertical-align: baseline;'>Verified</span>" :
      "<i class='fa fa-times-circle-o' aria-hidden='true' style='color: palevioletred;font-size: 25px;vertical-align: sub;'></i><span style='color: palevioletred;font-size: 14px;vertical-align: baseline;'>Unverified</span>"
  end
end  

app/views/private/settings/_change_password.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="evoxchangeUserSettingsModal">Change Password</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_for @member, url: change_password_settings_path, method: :put, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :old_password %> <!-- <i>(we need your current password to confirm your changes)</i> --><br />
          <%= f.password_field :old_password, autocomplete: "off", class: 'form-control', required: true %>            
        </div>

        <div class="form-group">
          <%= f.label :new_password %> <!-- <i>(leave blank if you don't want to change it)</i> --><br />
          <%= f.password_field :new_password, autocomplete: "off", class: 'form-control', required: true %>
        </div>

        <!-- <div class="form-group"> -->
          <%#= f.label :new_password_confirmation %><br />
          <%#= f.password_field :new_password_confirmation, autocomplete: "off", class: 'form-control' %>
        <!-- </div> -->

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Change</button> -->
        <%= f.submit :change, class: 'btn btn-primary' %>
      </div>

      <div class="modal-footer" style="display: none;">
        <span id="change_password_status"><i></i></span>
      </div>
    <% end %>
  </div>
</div>
<style>
  .modal-body * {
    user-select: none;
  }
</style>

app/views/private/settings/_update_profile.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="evoxchangeUserSettingsModal">Update Profile</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_tag update_profile_settings_path, method: :post, remote: true do %>
      <div class="modal-body">
        <div class="row form-group">
          <div class="col-6">
            <%= label_tag :first_name %>
            <%= text_field_tag 'member[first_name]', @current_details['first_name'], id: :profile_first_name, class: "form-control", placeholder: 'First name', required: true %>
          </div>

          <div class="col-6">
            <%= label_tag :last_name %>
            <%= text_field_tag 'member[last_name]', @current_details['last_name'], id: :profile_last_name, class: "form-control", placeholder: 'Last name', required: true %>
          </div>
        </div>

        <div class="row form-group mt-4">
          <div class="col-6">
            <%= label_tag :dob, "Date of birth" %>
            <div class="down-arrow">
              <%= date_field_tag 'member[dob]', @current_details['dob'], id: :profile_dob, class: 'datepicker-toggle form-control', 'data-date-format': 'yyyy-mm-dd', 'data-date-end-date': '-1d', placeholder: 'Date of birth', required: true %>
            </div>
          </div>

          <div class="col-6">
            <%= label_tag :country %>
            <%= select_tag 'member[country]', display_country(@current_details['country']), class: "form-control", required: true %>
          </div>
        </div>

        <div class="row form-group">
          <div class="col-12">
            <%= label_tag :address %>
            <%= text_field_tag 'member[address]', @current_details['address'], id: :profile_address, class: "form-control", placeholder: 'Address', required: true %>
          </div>
        </div>

        <div class="row form-group">
          <div class="col-6">
            <%= label_tag :city %>
            <%= text_field_tag 'member[city]', @current_details['city'], id: :profile_city, class: "form-control", placeholder: 'City', required: true %>
          </div>

          <div class="col-6">
            <%= label_tag :postcode %>
            <%= text_field_tag 'member[postcode]', @current_details['postcode'], id: :profile_postcode, class: "form-control", placeholder: 'Postcode', required: true %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag("CONFIRM", class: "btn btn-primary") unless @current_details.present? %>
      </div>

      <div class="modal-footer" style="display: none;">
        <span id="update_profile_status"><i></i></span>
      </div>
    <% end %>
  </div>
</div>
<style>
  .modal-body * {
    user-select: none;
  }
</style>

app/views/private/settings/_upload_documents.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="evoxchangeUserSettingsModal">Upload Documents</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_tag upload_documents_settings_path, method: :post, mutipart: true, id: 'member_upload_documents_form' do %>
      <div class="modal-body">
        <div class="row">
          <div class="field col-12 ">
            <label>Document upload</label>
            <%= file_field_tag 'document[upload]', {id: :document_upload, class: 'dropify form-control underlined', required: true, 'data-allowed-file-extensions': 'png jpg jpeg', 'data-max-file-size': '10M', 'data-default-file': (@current_details.present? ? image_url(ENV.fetch('BARONG_DOMAIN')+@current_details.last['upload']['url']) : false)} %>
            </br>
          </div>
        </div>
        <div class="row">
          <div class="field col-6">
            <%= label_tag :doc_type, 'Document type' %>
            <%= select_tag 'document[doc_type]', options_for_select(Member::DOC_TYPES, (@current_details.present? ? @current_details.last['doc_type'] : nil)), {id: :document_doc_type, class: 'form-control underlined', required: true} %>
          </div>

          <div class="field form-group">
            <%= label_tag :doc_expire, 'Document expiry' %>
            <div class="down-arrow">
              <%= date_field_tag 'document[doc_expire]', (@current_details.present? ? @current_details.last['doc_expire'] : nil), {id: :document_doc_expire, class: 'datepicker-toggle form-control underlined', 'data-date-format': 'yyyy-mm-dd', 'data-date-start-date': '+1d', placeholder: 'Expiry date', required: true} %>
            </div>
          </div>

          <div class="field form-group col-12">
            <%= label_tag :doc_number, 'Document number' %>
            <%= text_field_tag 'document[doc_number]', (@current_details.present? ? @current_details.last['doc_number'] : nil), id: :document_doc_number, class: 'form-control underlined', placeholder: 'AB123456', required: true %>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag 'Submit', class: 'btn btn-primary', id: 'document_verify_contact_submit' %>
      </div>

      <div class="modal-footer" style="display: none;">
        <span id="upload_documents_status"><i></i></span>
      </div>
    <% end %>
  </div>
</div>

<script>
  $('form#member_upload_documents_form').on('submit', function(e){
    e.preventDefault();
    var formData = new FormData('form#'+this.id);
    $.ajax({
      url: this.action,
      type: "POST",
      data: new FormData(this),
      contentType: false,
      cache: false,
      processData:false
    });
  })
</script>
<style>
  .modal-body * {
    user-select: none;
  }
</style>

app/views/private/settings/_verify_contact.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="evoxchangeUserSettingsModal">Verify Phone Number</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_tag verify_contact_settings_path, method: :put, remote: true do %>
      <div class="modal-body">
        <div class="form-group">
          <%= label_tag :country_code %><br />
          <%= number_field_tag 'member[country_code]', nil, {class: 'form-control', required: true, placeholder: 'Country Dial Code'} %>
        </div>
        <div class="form-group">
          <%= label_tag :phone_number %><br />
          <%= number_field_tag 'member[phone_number]', nil, {class: 'form-control', required: true, placeholder: 'Phone Number'} %>
        </div>

        <div class="form-group">
          <%= link_to 'Send Code', verify_contact_settings_path, class: 'btn btn-sm btn-success', id: 'contact_code_link' %> <span id="contact_code_status"><i></i></span>
        </div>

        <div class="form-group">
          <%= label_tag :verification_code %><br />
          <%= number_field_tag 'member[verification_code]', nil, {class: 'form-control', required: true, disabled: true, placeholder: 'Verification Code'} %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag 'Save', class: 'btn btn-primary', disabled: true, id: 'member_verify_contact_submit' %>
      </div>

      <div class="modal-footer" style="display: none;">
        <span id="verify_contact_status"><i></i></span>
      </div>
    <% end %>
  </div>
</div>

<script>
  $('#contact_code_link').click(function(e){
    e.preventDefault();
    country_code = $('input#member_country_code').val();
    phone_number = $('input#member_phone_number').val();
    $.post(this.href, {
      phone_number: (country_code+phone_number)
    }, function(response) {
      if (response.status) {
        $('span#contact_code_status i').text(response.message);
        $('input#member_verification_code, input#member_verify_contact_submit').removeAttr('disabled');
      } else {
        $('span#contact_code_status i').text(response.message);
      }
    })
  })
</script>
<style>
  .modal-body * {
    user-select: none;
  }
</style>

app/views/private/settings/change_password.js.erb
<% if @status %>
  <% flash[:notice] = @message %>
  window.location.reload()
<% else %>
  $('span#<%= params[:action] %>_status i').text('<%= @message %>').parents('div.modal-footer').show()
<% end %>

app/views/private/settings/update_profile.js.erb
<% if @status %>
  <% flash[:notice] = @message %>
  window.location.reload()
<% else %>
  $('span#<%= params[:action] %>_status i').text('<%= @message %>').parents('div.modal-footer').show()
<% end %>

app/views/private/settings/upload_documents.js.erb
<% if @status %>
  <% flash[:notice] = @message %>
  window.location.reload()
<% else %>
  $('span#<%= params[:action] %>_status i').text('<%= @message %>').parents('div.modal-footer').show()
<% end %>

app/views/private/settings/verify_contact.js.erb
<% if @status %>
  <% flash[:notice] = @message %>
  window.location.reload()
<% else %>
  $('span#<%= params[:action] %>_status i').text('<%= @message %>').parents('div.modal-footer').show()
<% end %>